const AllTilesData = {
    List: [
        { label: "GO", price: 0, icon: "➡️", color: "none", pos: "bottom", TilesDataIndex: null, order: 41 },
        { label: "Old Kent Road", price: 60, icon: "", color: "brown", pos: "bottom", TilesDataIndex: 35, order: 40 },
        { label: "Community Chest", price: 0, icon: "💰", color: "none", pos: "bottom", TilesDataIndex: 34, order: 39 },
        { label: "Whitechapel Road", price: 60, icon: "", color: "brown", pos: "bottom", TilesDataIndex: 33, order: 38 },
        { label: "Income Tax", price: 200, icon: "🔸", color: "none", pos: "bottom", TilesDataIndex: 32, order: 37 },
        { label: "King's Cross Station", price: 200, icon: "🚂", color: "none", pos: "bottom", TilesDataIndex: 31, order: 36 },
        { label: "The Angel Islington", price: 100, icon: "", color: "sky", pos: "bottom", TilesDataIndex: 30, order: 35 },
        { label: "Chance", price: 0, icon: "❓", color: "none", pos: "bottom", TilesDataIndex: 29, order: 34 },
        { label: "Euston Road", price: 100, icon: "", color: "sky", pos: "bottom", TilesDataIndex: 28, order: 33 },
        { label: "Pentonville Road", price: 120, icon: "", color: "sky", pos: "bottom", TilesDataIndex: 27, order: 32 },
        { label: "IN JAIL / JUST VISITING", price: 0, icon: "🚔", color: "none", pos: "left", TilesDataIndex: null, order: 31 },
        { label: "Pall Mall", price: 140, icon: "", color: "pink", pos: "left", TilesDataIndex: 17, order: 29 },
        { label: "Electric Company", price: 150, icon: "💡", color: "none", pos: "left", TilesDataIndex: 16, order: 27 },
        { label: "Whitehall", price: 140, icon: "", color: "pink", pos: "left", TilesDataIndex: 15, order: 25 },
        { label: "Northumberland Avenue", price: 160, icon: "", color: "pink", pos: "left", TilesDataIndex: 14, order: 23 },
        { label: "Marylebone Station", price: 200, icon: "🚂", color: "none", pos: "left", TilesDataIndex: 13, order: 21 },
        { label: "Bow Street", price: 180, icon: "", color: "orange", pos: "left", TilesDataIndex: 12, order: 19 },
        { label: "Community Chest", price: 0, icon: "💰", color: "none", pos: "left", TilesDataIndex: 11, order: 17 },
        { label: "Marlborough Street", price: 180, icon: "", color: "orange", pos: "left", TilesDataIndex: 10, order: 15 },
        { label: "Vine Street", price: 200, icon: "", color: "orange", pos: "left", TilesDataIndex: 9, order: 12 },
        { label: "FREE PARKING", price: 0, icon: "🅿️", color: "none", pos: "top", TilesDataIndex: null, order: 1 },
        { label: "Strand", price: 220, icon: "", color: "red", pos: "top", TilesDataIndex: 0, order: 2 },
        { label: "Chance", price: 0, icon: "❓", color: "none", pos: "top", TilesDataIndex: 1, order: 3 },
        { label: "Fleet Street", price: 220, icon: "", color: "red", pos: "top", TilesDataIndex: 2, order: 4 },
        { label: "Trafalgar Square", price: 240, icon: "", color: "red", pos: "top", TilesDataIndex: 3, order: 5 },
        { label: "Fenchurch St. Station", price: 200, icon: "🚂", color: "none", pos: "top", TilesDataIndex: 4, order: 6 },
        { label: "Leicester Square", price: 260, icon: "", color: "yellow", pos: "top", TilesDataIndex: 5, order: 7 },
        { label: "Coventry Street", price: 260, icon: "", color: "yellow", pos: "top", TilesDataIndex: 6, order: 8 },
        { label: "Water Works", price: 150, icon: "🚰", color: "none", pos: "top", TilesDataIndex: 7, order: 9 },
        { label: "Piccadilly", price: 280, icon: "", color: "yellow", pos: "top", TilesDataIndex: 8, order: 10 },
        { label: "GO TO JAIL", price: 100, icon: "🚓", color: "none", pos: "right", TilesDataIndex: null, order: 21 },
        { label: "Regent Street", price: 300, icon: "", color: "green", pos: "right", TilesDataIndex: 18, order: 14 },
        { label: "Oxford Street", price: 300, icon: "", color: "green", pos: "right", TilesDataIndex: 19, order: 16 },
        { label: "Community Chest", price: 0, icon: "💰", color: "none", pos: "right", TilesDataIndex: 20, order: 18 },
        { label: "Bond Street", price: 320, icon: "", color: "green", pos: "right", TilesDataIndex: 21, order: 20 },
        { label: "Liverpool St. Station", price: 200, icon: "🚂", color: "none", pos: "right", TilesDataIndex: 22, order: 22 },
        { label: "Chance", price: 0, icon: "❓", color: "none", pos: "right", TilesDataIndex: 23, order: 24 },
        { label: "Park Lane", price: 350, icon: "", color: "blue", pos: "right", TilesDataIndex: 24, order: 26 },
        { label: "Super Tax", price: 100, icon: "💍", color: "none", pos: "right", TilesDataIndex: 25, order: 28 },
        { label: "Mayfair", price: 400, icon: "", color: "blue", pos: "right", TilesDataIndex: 26, order: 30 },
    ],
};

export { AllTilesData };
