const AllTilesData = {
    List: [
        {
            label: "GO",
            price: 0,
            icon: "➡️",
            color: "none",
            order: "1",
            pos: "top",
            action: "collect", // Action: Collect $200 on passing
            value: 200, // Collect $200
        },
        {
            label: "strand",
            price: 220,
            icon: "",
            color: "red",
            order: "2",
            pos: "top",
        },
        {
            label: "chance",
            price: 0,
            icon: "❓",
            color: "none",
            order: "3",
            pos: "top",
            action: "chance", // Draw a chance card
        },
        {
            label: "fleet street",
            price: 220,
            icon: "",
            color: "red",
            order: "4",
            pos: "top",
        },
        {
            label: "trafalgar square",
            price: 240,
            icon: "",
            color: "none",
            order: "5",
            pos: "top",
        },
        {
            label: "fenchurch st. station",
            price: 200,
            icon: "🚂",
            color: "none",
            order: "6",
            pos: "top",
        },
        {
            label: "leicester square",
            price: 260,
            icon: "",
            color: "yellow",
            order: "7",
            pos: "top",
        },
        {
            label: "ceventry street",
            price: 200,
            icon: "",
            color: "yellow",
            order: "8",
            pos: "top",
        },
        {
            label: "water works",
            price: 150,
            icon: "🚰",
            color: "none",
            order: "9",
            pos: "top",
        },
        {
            label: "piccadilly",
            price: 280,
            icon: "",
            color: "yellow",
            order: "10",
            pos: "top",
        },
        {
            label: "Free Parking",
            price: 0,
            icon: "🅿️",
            color: "none",
            order: "11",
            pos: "left",
            action: "rest", // Rest space, no action
        },
        {
            label: "jail/just visiting",
            price: 0,
            icon: "🚔",
            color: "none",
            order: "13",
            pos: "top",
            action: "jail", // Indicates Jail or Just Visiting
        },
        {
            label: "vine street",
            price: 200,
            icon: "",
            color: "orange",
            order: "12",
            pos: "left",
        },
        {
            label: "marlborough street",
            price: 200,
            icon: "",
            color: "orange",
            order: "15",
            pos: "left",
        },
        {
            label: "community chest",
            price: 0,
            icon: "💰",
            color: "none",
            order: "17",
            pos: "left",
            action: "community", // Draw a Community Chest card
        },
        {
            label: "bow street",
            price: 180,
            icon: "",
            color: "orange",
            order: "19",
            pos: "left",
        },
        {
            label: "Go to Jail",
            price: 0,
            icon: "🚨",
            color: "none",
            order: "22",
            pos: "bottom",
            action: "goToJail", // Sends the player to jail
        },
        {
            label: "northumrl'd avenue",
            price: 160,
            icon: "",
            color: "pink",
            order: "23",
            pos: "left",
        },
        {
            label: "whitehall",
            price: 140,
            icon: "",
            color: "pink",
            order: "25",
            pos: "left",
        },
        {
            label: "electric company",
            price: 150,
            icon: "💡",
            color: "none",
            order: "27",
            pos: "left",
        },
        {
            label: "pall mall",
            price: 140,
            icon: "",
            color: "pink",
            order: "29",
            pos: "left",
        },
        {
            label: "regent street",
            price: 300,
            icon: "",
            color: "green",
            order: "14",
            pos: "right",
        },
        {
            label: "bond street",
            price: 320,
            icon: "",
            color: "green",
            order: "20",
            pos: "right",
        },
        {
            label: "park lane",
            price: 350,
            icon: "",
            color: "blue",
            order: "26",
            pos: "right",
        },
        {
            label: "super tax",
            price: 100,
            icon: "💍",
            color: "none",
            order: "28",
            pos: "right",
            action: "tax", // Pay tax
            value: 100, // Tax amount
        },
        {
            label: "mayfair",
            price: 400,
            icon: "",
            color: "blue",
            order: "30",
            pos: "right",
        },
        {
            label: "income tax",
            price: 0,
            icon: "🔸",
            color: "none",
            order: "31",
            pos: "bottom",
            action: "tax", // Pay tax
            value: 200, // Tax amount
        },
        {
            label: "pentonville road",
            price: 120,
            icon: "",
            color: "sky",
            order: "32",
            pos: "bottom",
        },
        {
            label: "euston road",
            price: 100,
            icon: "",
            color: "sky",
            order: "33",
            pos: "bottom",
        },
        {
            label: "chance",
            price: 0,
            icon: "❓",
            color: "none",
            order: "34",
            pos: "bottom",
            action: "chance", // Draw a chance card
        },
        {
            label: "the angel, islington",
            price: 100,
            icon: "",
            color: "sky",
            order: "35",
            pos: "bottom",
        },
        {
            label: "kings cross station",
            price: 200,
            icon: "🚂",
            color: "none",
            order: "36",
            pos: "bottom",
        },
        {
            label: "community chest",
            price: 0,
            icon: "💰",
            color: "none",
            order: "39",
            pos: "bottom",
            action: "community", 
        },
        {
            label: "whitechapel road",
            price: 60,
            icon: "",
            color: "brown",
            order: "38",
            pos: "bottom",
        },
        {
            label: "old kent road",
            price: 60,
            icon: "",
            color: "brown",
            order: "40",
            pos: "bottom",
        },
    ],
};

export { AllTilesData };
