const AllTilesData = {
    List: [
        { label: "GO", price: 0, icon: "➡️", color: "none", pos: "bottom", TilesDataIndex: null },
        { label: "Old Kent Road", price: 60, icon: "", color: "brown", pos: "bottom", TilesDataIndex: 39 },
        { label: "Community Chest", price: 0, icon: "💰", color: "none", pos: "bottom", TilesDataIndex: 38 },
        { label: "Whitechapel Road", price: 60, icon: "", color: "brown", pos: "bottom", TilesDataIndex: 37 },
        { label: "Income Tax", price: 200, icon: "🔸", color: "none", pos: "bottom", TilesDataIndex: 36 },
        { label: "King's Cross Station", price: 200, icon: "🚂", color: "none", pos: "bottom", TilesDataIndex: 35 },
        { label: "The Angel Islington", price: 100, icon: "", color: "sky", pos: "bottom", TilesDataIndex: 34 },
        { label: "Chance", price: 0, icon: "❓", color: "none", pos: "bottom", TilesDataIndex: 33 },
        { label: "Euston Road", price: 100, icon: "", color: "sky", pos: "bottom", TilesDataIndex: 32 },
        { label: "Pentonville Road", price: 120, icon: "", color: "sky", pos: "bottom", TilesDataIndex: 31 },
        { label: "IN JAIL / JUST VISITING", price: 0, icon: "🚔", color: "none", pos: "left", TilesDataIndex: null },
        { label: "Pall Mall", price: 140, icon: "", color: "pink", pos: "left", TilesDataIndex: 17 },
        { label: "Electric Company", price: 150, icon: "💡", color: "none", pos: "left", TilesDataIndex: 16 },
        { label: "Whitehall", price: 140, icon: "", color: "pink", pos: "left", TilesDataIndex: 15 },
        { label: "Northumberland Avenue", price: 160, icon: "", color: "pink", pos: "left", TilesDataIndex: 14 },
        { label: "Marylebone Station", price: 200, icon: "🚂", color: "none", pos: "left", TilesDataIndex: 13 },
        { label: "Bow Street", price: 180, icon: "", color: "orange", pos: "left", TilesDataIndex: 12 },
        { label: "Community Chest", price: 0, icon: "💰", color: "none", pos: "left", TilesDataIndex: 11 },
        { label: "Marlborough Street", price: 180, icon: "", color: "orange", pos: "left", TilesDataIndex: 10 },
        { label: "Vine Street", price: 200, icon: "", color: "orange", pos: "left", TilesDataIndex: 9 },
        { label: "FREE PARKING", price: 0, icon: "🅿️", color: "none", pos: "top", TilesDataIndex: null },
        { label: "Strand", price: 220, icon: "", color: "red", pos: "top", TilesDataIndex: 0 },
        { label: "Chance", price: 0, icon: "❓", color: "none", pos: "top", TilesDataIndex: 1 },
        { label: "Fleet Street", price: 220, icon: "", color: "red", pos: "top", TilesDataIndex: 2 },
        { label: "Trafalgar Square", price: 240, icon: "", color: "red", pos: "top", TilesDataIndex: 3 },
        { label: "Fenchurch St. Station", price: 200, icon: "🚂", color: "none", pos: "top", TilesDataIndex: 4 },
        { label: "Leicester Square", price: 260, icon: "", color: "yellow", pos: "top", TilesDataIndex: 5 },
        { label: "Coventry Street", price: 260, icon: "", color: "yellow", pos: "top", TilesDataIndex: 6 },
        { label: "Water Works", price: 150, icon: "🚰", color: "none", pos: "top", TilesDataIndex: 7 },
        { label: "Piccadilly", price: 280, icon: "", color: "yellow", pos: "top", TilesDataIndex: 8 },
        { label: "GO TO JAIL", price: 100, icon: "🚓", color: "none", pos: "right", TilesDataIndex: null },
        { label: "Regent Street", price: 300, icon: "", color: "green", pos: "right", TilesDataIndex: 19 },
        { label: "Oxford Street", price: 300, icon: "", color: "green", pos: "right", TilesDataIndex: 20 },
        { label: "Community Chest", price: 0, icon: "💰", color: "none", pos: "right", TilesDataIndex: 21 },
        { label: "Bond Street", price: 320, icon: "", color: "green", pos: "right", TilesDataIndex: 22 },
        { label: "Liverpool St. Station", price: 200, icon: "🚂", color: "none", pos: "right", TilesDataIndex: 23 },
        { label: "Chance", price: 0, icon: "❓", color: "none", pos: "right", TilesDataIndex: 24 },
        { label: "Park Lane", price: 350, icon: "", color: "blue", pos: "right", TilesDataIndex: 25 },
        { label: "Super Tax", price: 100, icon: "💍", color: "none", pos: "right", TilesDataIndex: 26 },
        { label: "Mayfair", price: 400, icon: "", color: "blue", pos: "right", TilesDataIndex: 27 },
    ],
};

export { AllTilesData };
