var TilesData = {
  List: [
    {
      label: "strand",
      price: 220,
      icon: "",
      color: "red",
      order: "2",
      pos: "top",
      ownerId: null,
    },
    {
      label: "chance",
      price: 0,
      icon: "❓",
      color: "none",
      order: "3",
      pos: "top",
      ownerId: 4,
    },
    {
      label: "fleet street",
      price: 220,
      icon: "",
      color: "red",
      order: "4",
      pos: "top",
      ownerId: 4,
    },
    {
      label: "trafalgar square",
      price: 240,
      icon: "",
      color: "none",
      order: "5",
      pos: "top",
      ownerId: null,
    },
    {
      label: "fenchurch st. station",
      price: 200,
      icon: "🚂",
      color: "none",
      order: "6",
      pos: "top",
      ownerId: null,
    },
    {
      label: "leicester square",
      price: 260,
      icon: "",
      color: "yellow",
      order: "7",
      pos: "top",
      ownerId: null,
    },
    {
      label: "ceventry street",
      price: 200,
      icon: "",
      color: "yellow",
      order: "8",
      pos: "top",
      ownerId: null,
    },
    {
      label: "water works",
      price: 150,
      icon: "🚰",
      color: "none",
      order: "9",
      pos: "top",
      ownerId: null,
    },
    {
      label: "piccadilly",
      price: 280,
      icon: "",
      color: "yellow",
      order: "10",
      pos: "top",
      ownerId: null,
    },
    {
      label: "vine street",
      price: 200,
      icon: "",
      color: "orange",
      order: "12",
      pos: "left",
      ownerId: null,
    },
    {
      label: "marlborog'h street",
      price: 200,
      icon: "",
      color: "orange",
      order: "15",
      pos: "left",
      ownerId: null,
    },
    {
      label: "community chest",
      price: 0,
      icon: "💰",
      color: "none",
      order: "17",
      pos: "left",
      ownerId: 4,
    },
    {
      label: "bow street",
      price: 180,
      icon: "",
      color: "orange",
      order: "19",
      pos: "left",
      ownerId: null,
    },
    {
      label: "marylebone station",
      price: 200,
      icon: "🚂",
      color: "none",
      order: "21",
      pos: "left",
      ownerId: null,
    },
    {
      label: "northumrl'd avenue",
      price: 160,
      icon: "",
      color: "pink",
      order: "23",
      pos: "left",
      ownerId: null,
    },
    {
      label: "whitehall",
      price: 140,
      icon: "",
      color: "pink",
      order: "25",
      pos: "left",
      ownerId: null,
    },
    {
      label: "electric company",
      price: 150,
      icon: "💡",
      color: "none",
      order: " 27",
      pos: "left",
      ownerId: null,
    },
    {
      label: "pall mall",
      price: 140,
      icon: "",
      color: "pink",
      order: "29",
      pos: "left",
      ownerId: null,
    },
    {
      label: "regent street",
      price: 300,
      icon: "",
      color: "green",
      order: "14",
      pos: "right",
      ownerId: null,
    },
    {
      label: "oxford street",
      price: 300,
      icon: "",
      color: "green",
      order: "16",
      pos: "right",
      ownerId: null,
    },
    {
      label: "community chest",
      price: 0,
      icon: "💰",
      color: "none",
      order: "18",
      pos: "right",
      ownerId: 4,
    },
    {
      label: "bond street",
      price: 320,
      icon: "",
      color: "green",
      order: "20",
      pos: "right",
      ownerId: null,
    },
    {
      label: "liverpool st. station",
      price: 320,
      icon: "🚂",
      color: "none",
      order: "22",
      pos: "right",
      ownerId: null,
    },
    {
      label: "chance",
      price: 0,
      icon: "",
      color: "none",
      order: "24",
      pos: "right",
      ownerId: 4,
    },
    {
      label: "park lane",
      price: 350,
      icon: "",
      color: "blue",
      order: "26",
      pos: "right",
      ownerId: null,
    },
    {
      label: "super tax",
      price: 100,
      icon: "💍",
      color: "none",
      order: "28",
      pos: "right",
      ownerId: null,
    },
    {
      label: "mayfair",
      price: 400,
      icon: "",
      color: "blue",
      order: "30",
      pos: "right",
      ownerId: null,
    },
    {
      label: "pentonville road",
      price: 120,
      icon: "",
      color: "sky",
      order: "32",
      pos: "bottom",
      ownerId: null,
    },
    {
      label: "euston road",
      price: 100,
      icon: "",
      color: "sky",
      order: "33",
      pos: "bottom",
      ownerId: null,
    },
    {
      label: "chance",
      price: 0,
      icon: "❓",
      color: "none",
      order: "34",
      pos: "bottom",
      ownerId: 4,
    },
    {
      label: "the angel, islington",
      price: 100,
      icon: "",
      color: "sky",
      order: "35",
      pos: "bottom",
      ownerId: null,
    },
    {
      label: "kings cross station",
      price: 200,
      icon: "🚂",
      color: "none",
      order: "36",
      pos: "bottom",
      ownerId: null
    },
    {
      label: "income tax",
      price: 200,
      icon: "🔸",
      color: "none",
      order: "37",
      pos: "bottom",
      ownerId: 4,
    },
    {
      label: "whitechapel road",
      price: 60,
      icon: "",
      color: "brown",
      order: "38",
      pos: "bottom",
      ownerId: null,
    },
    {
      label: "community chest",
      price: 0,
      icon: "💰",
      color: "none",
      order: "39",
      pos: "bottom",
      ownerId: 4,
    },
    {
      label: "old kent road",
      price: 60,
      icon: "",
      color: "brown",
      order: "40",
      pos: "bottom",
      ownerId: null,
    },
  ],
}


export { TilesData }